---
 - name: Install pkg
   apt:
     pkg: "{{ pkg }}"
     state: present
     update_cache: false
   vars:
     pkg:
       - nginx
       - certbot
       - python-certbot-nginx
       - apache2-utils
 
 
 - name: Create directory letsencrypt 
   file: path=/srv/www/letsencrypt/.well-known/acme-challenge/ state=directory owner=root group=root

 - name: Add conf letsencrypt
   copy: src=letsencrypt.conf dest=/etc/nginx/ owner=root group=root
