---
- hosts: backend
  become: true
  tasks:
    - name: Install GIT
      apt:
        name: git
        state: present

    - name: Get Repository
      git: repo=https://github.com/strikeblack91/EPITECH-NSA-BACKEND
        dest=/home/vagrant/backend
        force=yes
        accept_hostkey=yes

    - name: install PHP + PKG
      apt:
        name:
          - php
          - php-curl
          - php-mbstring
          - php-xml
          - php-cli
          - unzip

    - name: Update PKG
      apt: update_cache=yes force_apt_get=yes

    - name: Download Composer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/installer

    - name: install Composer
      shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
      args:
        creates: /usr/local/bin/composer

    - name: Rename Composer
      shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
      args:
        creates: /usr/local/bin/composer

    - name: Make Composer executable
      file:
        path: /usr/local/bin/composer
        mode: a+x
        state: file

    - name: Install composer dependencies
      shell: yes 'y' | composer update --working-dir=/home/vagrant/backend

    - name: Add service
      shell: mv /home/vagrant/backend/nsa_backend.service /lib/systemd/system/
    
    - name: Stop apache
      shell: sudo service apache2 stop

    - name: Run server
      service:
        name: nsa_backend
        state: restarted
