- name: Setup server
  hosts: FRONT
  connection: ssh
  roles:
    - Setup

- name: Setup Nginx
  hosts: FRONT
  connection: ssh
  roles:
    - Nginx

- name: Building Application and Deploy
  hosts: FRONT
  connection: ssh
  roles:
    - Deployment