# - git:
#     repo: ''
#     dest: '/var/www/front'
#     force: yes
#     update: yes

- name: Copy front folder
  ansible.builtin.copy:
    src: files/front
    dest: /var/www/front/

- name: Npm install
  npm:
    path: '/var/www/front/front/'

- name: Copy environnement
  template:
    src: files/environment.prod.ts
    dest: /var/www/front/front/src/environments

- name: Install dependencies
  command: ng build --prod
  args:
    chdir: '/var/www/front/front/'

- name: Copy site in nginx folder
  shell: mv /var/www/front/front/dist/front/* /var/www/front

- name: Restart nginx
  service:
    name: nginx
    state: restarted