- name: Setup
  apt: 
    upgrade: dist

- name: Installing Python
  apt:
    name:
      - python3
      - python3-pip
      - python-pip
      - python-apt
      - git
    state: latest

- name: "Setup Nodejs"
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: "Add Nodejs repository"
  apt_repository:
    repo: deb https://deb.nodesource.com/node_12.x bionic main

- name: "Installing Nodejs"
  apt:
    update_cache: yes
    name: nodejs
    state: present

- name: "Installing Angular"
  become: true
  become_user: root
  shell: npm install -g --save-dev @angular/cli@latest