---
- name: add {{app_user}} to sudo
  become: true
  ansible.builtin.command: usermod -a -G sudo {{app_user}}

- name: Install pkg base
  become: true
  apt:
    pkg: "{{ pkg }}"
    state: present
    update_cache: false
  vars:
    pkg:
      - fail2ban
      - htop
      - ngrep
      - iotop
      - bmon
      - php
      - php-fpm
      - sysstat
      - bash-completion
      - aptitude
      - openssl
      - vim
      - curl
      - openssl
      - pwgen
      - apt-transport-https
      - gcc
      - g++
      - make
      - git
      - git-flow
      - sudo
      - acl

- name: Add folder .ssh {{app_user}}
  file:
    path: /home/{{app_user}}/.ssh
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0755"

- name: add private key {{app_user}}
  copy:
    src: id_rsa
    dest: /home/{{app_user}}/.ssh/id_ed25519
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0600"
  when: not ansible_check_mode
